name: Latest blog post
on:
    push:
        branches: [ "main" ] 
    schedule:
        - cron: '30 1,13 * * *'
jobs:
    update-readme-with-blog:
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: generate github-contribution-grid-snake.svg
              uses: Platane/snk@master
              with:
                  github_user_name: ${{ github.repository_owner }}
                  outputs: |
                    dist/github-snake.svg
                    dist/github-snake-dark.svg?palette=github-dark
                    dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

            - name: push github-contribution-grid-snake.svg to the output branch
              uses: crazy-max/ghaction-github-pages@v2.6.0
              with:
                target_branch: output
                build_dir: dist
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
