name: Latest blog post
on:
    push:
        branches: [ "main" ] 
#     schedule:
#         - cron: '30 1,13 * * *'
jobs:
    update-readme-with-blog:
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                  max_post_count: "5"
                  feed_list: "https://medium.com/feed/@yantong0116"
            - uses: yoshi389111/github-profile-3d-contrib@0.7.0
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  USERNAME: ${{ github.repository_owner }}
                  
            - name: generate github-contribution-grid-snake.svg
              uses: Platane/snk/svg-only@v2
              with:
                  github_user_name: ${{ github.repository_owner }}
                  outputs: |
                    dist/github-contribution-grid-snake.svg
                    dist/github-contribution-grid-snake-dark.svg?palette=github-dark
