name: Latest blog post
on:
    push:
        branches: [ "main" ] 
    #schedule:
        # Runs at 9pm UTC  
        #- cron: "20 16 * * *"
    workflow_dispatch:
jobs:
    update-readme-with-blog:
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                  max_post_count: "5"
                  feed_list: "https://medium.com/feed/@yantong0116"
            - name: generate github-contribution-grid-snake.svg
              uses: Platane/snk/svg-only@v2
              with:
                  github_user_name: ${{ github.repository_owner }}
                  outputs: |
                    dist/github-contribution-grid-snake.svg
                    dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            - uses: th3c0d3br34ker/github-readme-info@master
              with:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  TIMEZONE: "Asia/Kolkata"
                  SHOW_LINES_OF_CODE: "True"
                  SHOW_PROFILE_VIEWS: "True"
                  SHOW_DAILY_COMMIT: "True"
                  SHOW_WEEKLY_COMMIT: "True"
                  SHOW_LANGUAGE: "True"
                  SHOW_TOTAL_CONTRIBUTIONS: "True"
